### ISSUE TITLE
Search Field Behavior 

### ISSUE THREAD

**Issue by deeken** [cooperhewitt/collection#4]
There is a discrepancy in the ‘Search’ input field in the menu after scrolling.

Please scroll down so it becomes truncated and then click the search button on the url;
http://www.cooperhewitt.org/events/current-exhibitions/

If you click the icon it does the correct behavior, it would be great to keep this behavior consistent.

If you click the ‘Search’ text it shows an incorrect truncated search field.

Thanks!
Ken

**Comment by micahwalter** [comment]
moving this to our internal mainsite repo
